version: "3.7"
services:
    motioneye:
        container_name: motioneye 
        image: ccrisan/motioneye:master-armhf
        restart: always
        ports:
            - 8765:8765
            - 8081:8081
        volumes:
            - /etc/localtime:/etc/localtime:ro
            - /media/usbstick/motioneye:/etc/motioneye
            - /media/usbstick:/var/lib/motioneye
        privileged: true
        environment:
            - LD_LIBRARY_PATH=/opt/vc/lib
        devices:
            - "/dev/vchiq"
            - "/dev/video0"
            - "/dev/video10"
            - "/dev/video11"
            - "/dev/video12"
            - "/dev/video13"
            - "/dev/video14"
            - "/dev/video15"
            - "/dev/video16"
            - "/dev/video17"
            - "/dev/video18"
