version: "3.7"
services:
  analyzer:
     container_name: analyzer 
     build:
        context: .
        dockerfile: Dockerfile
     network_mode: host
     restart: always
     volumes:
        - /dev/bus/usb:/dev/bus/usb
        - /opt/vc:/opt/vc
        - ./input:/app/input
        - ./done:/app/done
        - ./output:/app/output
        - ./models:/app/models
        - /tmp/.X11-unix:/tmp/.X11-unix
     environment:
        LD_LIBRARY_PATH: /opt/vc/lib
        DISPLAY:
     devices:
        - "/dev/vchiq:/dev/vchiq"
     privileged: true
