version: "3.7"
services:
    analyzer:
        container_name: analyzer
        build:
            context: .
            dockerfile: Dockerfile
        network_mode: host
        restart: "no"
        volumes:
            - ./../../input:/app/input
            - ./../../done:/app/done
            - ./../../error:/app/error
            - ./../../output:/app/output
            - ./models:/app/models
            - ./python:/app/python 
            - ./config.json:/app/config.json
        environment:
            - OBJECT_DETECTION_THREADS=${OBJECT_DETECTION_THREADS}
        privileged: true
