version: "3.7"
services:
    analyzer:
        container_name: analyzer 
        build:
            context: .
            dockerfile: Dockerfile
        network_mode: host
        restart: always
        volumes:
            - ./input:/app/input
            - ./done:/app/done
            - ./output:/app/output
            - ./models:/app/models
        environment:
            - OBJECT_DETECTION_THREADS=${OBJECT_DETECTION_THREADS}
        privileged: true
