version: "3.7"
services:
    analyzer:
        container_name: analyzer 
        build:
            context: .
            dockerfile: Dockerfile_raspi
        network_mode: host
        restart: always
        volumes:
            - /media/usbstick/raw:/app/input
            - /media/usbstick/analyzed:/app/done
            - /media/usbstick/data:/app/output
            - /media/usbstick/error:/app/error
            - ./config_raspi.json:/app/config.json
            - ./models:/app/models
        privileged: true
