version: "3.7"
services:
    webhook:
        container_name: webhook 
        build:
            context: .
            dockerfile: Dockerfile_raspi
        restart: always
        command: ["-verbose", "-hooks=/etc/webhook/hooks.json", "-urlprefix="]
        ports:
            - 80:9000
        volumes:
            - ./hooks:/etc/webhook
        privileged: true