FROM        golang:alpine3.11 AS build
WORKDIR     /go/src/github.com/adnanh/webhook
ENV         WEBHOOK_VERSION 2.8.0
RUN         apk add --update -t build-deps curl libc-dev gcc libgcc
RUN         curl -L --silent -o webhook.tar.gz https://github.com/adnanh/webhook/archive/${WEBHOOK_VERSION}.tar.gz
RUN         tar -xzf webhook.tar.gz --strip 1
RUN         go get -d
RUN         go build -o /usr/local/bin/webhook
RUN         apk del --purge build-deps
RUN         rm -rf /var/cache/apk/*
RUN         rm -rf /go

FROM        alpine:3.11
LABEL version=1.0
COPY        --from=build /usr/local/bin/webhook /usr/local/bin/webhook
WORKDIR     /etc/webhook
RUN         apk update && apk del openssh openssh-client && apk add openssh-client && apk add sshpass
VOLUME      ["/etc/webhook"]
EXPOSE      9000
ENTRYPOINT  ["/usr/local/bin/webhook"]